# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6598b7af2f0cb141fb59c9907c661f39a82dffb2d8147bd7527ee57715f1b21b3f69c3751ad60e6a58cd3a6e65e2c4f10ad00ebcd81ad4e56600eceae8c9dad6

test:
  secret_key_base: b91ab93825d5438270c8af1f570a7355b3d0dd44aefb707458d3ed28930182ed400fd0e539d547ea581a94a4c7e14b70498c31d3547398f707d5e38f010ec8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
